### ISSUE TITLE
TC CLI Azure Devops Pipeline: Error: process.stdout.clearLine is not a function

### ISSUE THREAD

**Issue by wavveen** [rangav/thunder-client-support#1009]
**Describe the bug**
When trying to execute a request with TC CLI in a Azure Devops Pipeline I'm getting the following error:
process.stdout.clearLine is not a function

![image](https://user-images.githubusercontent.com/6557188/217758773-fe769ed8-3984-4fb0-a490-f8383542f4c5.png)

This answer on Stackoverflow tells me it's because _clearLine()_ is undefined when process.stdout is not a tty: https://stackoverflow.com/a/43396582

When running the same command in a terminal on my local there is no issue.

**To Reproduce**
Here is the YML of the Azure pipeline:
```
trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: Install Node
  inputs:
    versionSource: 'spec'
    versionSpec: 18.12.1
    
- task: Npm@1
  displayName: Install ThunderClient/CLI
  inputs:
    workingDir: '$(System.DefaultWorkingDirectory)'
    command: 'custom'
    customCommand: 'install -g @thunderclient/cli'

- task: CmdLine@2
  displayName: Create reports directory
  inputs:
    workingDir: '$(System.DefaultWorkingDirectory)'
    script: mkdir -p thunder-reports
    
- task: PowerShell@2
  inputs:
    workingDir: '$(System.DefaultWorkingDirectory)'  
    targetType: inline
    script: tc dummy --report csv
```

The working directory contains the "thunder-tests" folder which has a collection that contains the "dummy" request.

**Your Team Size Using TC:**
20
