### ISSUE TITLE
Test fails with exit code 0

### ISSUE THREAD

**Issue by abmohan** [rangav/thunder-client-support#1041]
**Describe the bug**
When I run `npx tc --col 'my collection' --stop-on-fail --report html` and check the HTML output report, I see that one test failed. However, when I run `echo $?` in the shell, it returns code `0`.

I'm trying to integrate my shell with the python `pre-commit` tool. This is the entry in the configuration file:
```
  - repo: local
    hooks:
      - id: thunder-tests
        name: Thunder Client E2E API Tests
        description: Run E2E API tests using Thunder client

        entry: tc --col 'my collection' --stop-on-fail --report html
        language: node
 ```

It shows that my tests have passed (and allows me to proceed with my commit) even though one of the tests failed. My guess is that it's looking at the exit code to determine whether or not the test passed

**To Reproduce**
Have a failing test in your collection and run `tc --col 'my collection' --stop-on-fail --report html`, and type `echo $?` immediately afterwards.

**Expected behavior**
`echo $?` should result in a non-zero exit code

**Platform:** 
 - OS: Mac OS X - Ventura 13.2.1
 - vscode version: 1.75.1
 - extension version: 2.5.0
 - node.js version: v19.6.1

**Your Team Size Using TC:**
We have a small engineering team of 4. All 4 of us are using the product
