### ISSUE TITLE
CLI runs slow in CI/CD pipeline

### ISSUE THREAD

**Issue by azplanlos** [rangav/thunder-client-support#1399]
**Describe the bug**
TC CLI performs slow in our GitLab CI/CD pipeline, runtime is approx. 3-4 times slower than running requests via CLI on the local machine against the same endpoint when running a medium sized collection. Running 144 requests takes around 25 minutes in the pipeline while running in a couple of minutes locally. 

**Platform:** 
 - OS: linux

**Are you using the free version/paid version/trial:**
paid version

**Comment by rangav** [comment]
Hi @azplanlos Thanks for reporting the issue. 

What differences have you noticed in the Html report generated from local CLI and Gitlab CI/CD?

If you can share any further details of the issue, which might help to resolve the issue.

**Comment by azplanlos** [comment]
The execution times look approx. the same. Interesting thing is, if I add up the request execution times I get approx. 3-4 Minutes of time but total execution time is 25 Minutes.

**Comment by rangav** [comment]
- Did you add a delay in between requests?
- Do you have scripts that take longer time to execute?
- Do you retry logic that is working correctly?

**Comment by azplanlos** [comment]
No, there is no delay between requests and only simple pre-request and post-request scripts. No retry used.

**Comment by rangav** [comment]
What are duration time values in the Html Report?

<img width="1035" alt="Screenshot 2023-11-10 at 09 53 11" src="https://github.com/rangav/thunder-client-support/assets/8637550/7e1d646c-20a2-44ff-a61c-8b7c3cc209a8">

**Comment by azplanlos** [comment]
local: Total Duration: 78762ms
CI/CD: Total Duration: 1968393ms

same collection, run command: tc --col <colname> --log 8 --report cli,html --var-data url=[...,token_endpoint=...,client_id=...,client_secret=...](...,token_endpoint=...,client_id=...,client_secret=...) --ws <ws_name> --env <env_name>

**Comment by rangav** [comment]
Something is an issue with Gitlab CI/Cd runtime.

Is it possible for you to create a sample collection using Test url - https://www.thunderclient.com/welcome 
and some sample test scripts that can re-produce the issue, so I can test it myself.

**Comment by rangav** [comment]
Hi @azplanlos the issue could http library used. Can you change to axios libary.

In your `.vscode` folder-> open `settings.json` and add below line

`"thunder-client.httpLibrary": "axios"`

Can you please test with axios and let me know the result

**Comment by azplanlos** [comment]
unfortunately this doesn't make a difference.

**Comment by rangav** [comment]
Thanks for confirmation. Did you check with other teams in your company do they have similar issue?

**Comment by azplanlos** [comment]
Hi @rangav, we did a little more digging and are able to reproduce the behaviour by running thunder client in a docker container and limiting the CPU ressources to the values used in our pipeline. First finding here is that using a node.js base image with alpine instead of Ubuntu runs much faster, but anyway maybe you have some more tooling to see how the performance could be improved more.

I used this Dockerfile for creating an alpine based image:

```
FROM node:21-alpine

RUN npm i -g @thunderclient/cli

VOLUME ["/home/tests"]

WORKDIR "/home/tests"
ENTRYPOINT ["/usr/local/bin/tc"]
CMD ["--help"]
```

and this docker-compose to setup our service and run the container with limited ressources on my Macbook:

```
version: "3.8"

services:
  testrunner:
    image: tc-runner:latest
    command: "--col 'collection_name' --env 'environment' --report 'cli,html' --var-data 'url=...' --log 0"
    volumes:
      - ./tests:/home/tests
    depends_on:
      - ...
    deploy:
      resources:
        limits:
          cpus: '0.150'
          memory: 375M
        reservations:
          cpus: '0.150'
          memory: 375M

```

My findings are: runtime for our collection locally is around 55 seconds, in docker with Ubuntu 16 minutes, with alpine and Debian bookworm approx 7-8 minutes.
