### ISSUE TITLE
Run request multiple times with different parameters

### ISSUE THREAD

**Issue by rokbjc** [rangav/thunder-client-support#754]
I would like to test single endpoint with permutation of multiple combination of parameters. Lets say we have request like this:
```
/chart?period={{period}}&asset={{asset}}&language={{language}}
```
Currently i need to create one request for each combination I want so in case of following options:
```
period = [1, 7, 30]
asset = ["BTC", "ETH"]
language = ["en", "de"]
```
I need to copy single request 12 times and redefine its parameters. It would be nice if I could run single request with all permutations or maybe randomly n-times.

There is similar implementation of this in software artillery where parameters are set randomly. Config looks like this:
``` yml
config:
  target: "https://localhost"
  http:
    timeout: 5
  phases:
    - duration: 120
      arrivalRate: 100
      rampTo: 5000
  variables:
    asset:
      - "btc"
      - "eth"
    lang:
      - "en"
      - "de"
    period:
      - "1"
      - "7"
      - "30"
scenarios:
  - name: "Get Chart"
    flow:
      - get:
          url: "/chart?period={{period}}&asset={{asset}}&language={{language}}"
```
